# Generated by Django 3.1.4 on 2020-12-25 02:24

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('testproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproject.thing')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testproject_taggedthing_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='thing',
            name='objects',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='testproject.TaggedThing', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
