# Generated by Django 3.1.4 on 2021-01-16 20:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('testproject', '0002_auto_20201225_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='objects',
        ),
        migrations.AddField(
            model_name='thing',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='testproject.TaggedThing', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
