# Generated by Django 3.1.4 on 2021-01-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('testproject', '0003_auto_20210116_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
