# Generated by Django 3.1.4 on 2021-01-16 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0004_actortag_directortag_languagetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTaggedThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproject.thing')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testproject_languagetaggedthing_items', to='testproject.languagetag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorTaggedThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproject.thing')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testproject_directortaggedthing_items', to='testproject.directortag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActorTaggedThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testproject.thing')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testproject_actortaggedthing_items', to='testproject.actortag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
