# Generated by Django 3.1.4 on 2021-01-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0005_actortaggedthing_directortaggedthing_languagetaggedthing'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actortaggedthing',
            unique_together={('tag', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='directortaggedthing',
            unique_together={('tag', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='languagetaggedthing',
            unique_together={('tag', 'content_object')},
        ),
    ]
