# Generated by Django 3.1.4 on 2021-01-17 03:08

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('testproject', '0006_auto_20210116_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='testproject.TaggedThing', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
