# Generated by Django 3.1.4 on 2021-01-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('testproject', '0007_auto_20210117_0308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorTag',
            new_name='ActorTagType',
        ),
        migrations.RenameModel(
            old_name='DirectorTag',
            new_name='DirectorTagType',
        ),
        migrations.RenameModel(
            old_name='LanguageTag',
            new_name='LanguageTagType',
        ),
    ]
