# Generated by Django 3.1.4 on 2021-01-17 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('testproject', '0008_auto_20210117_0320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageTagType',
            new_name='LanguageTypedTag',
        ),
        migrations.RenameModel(
            old_name='DirectorTagType',
            new_name='DirectorTypedTag',
        ),
        migrations.RenameModel(
            old_name='ActorTagType',
            new_name='ActorTypedTag',
        ),
    ]
