# Generated by Django 3.1.4 on 2021-01-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0009_auto_20210117_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actortaggedthing',
            old_name='tag',
            new_name='typed_tag',
        ),
        migrations.RenameField(
            model_name='directortaggedthing',
            old_name='tag',
            new_name='typed_tag',
        ),
        migrations.RenameField(
            model_name='languagetaggedthing',
            old_name='tag',
            new_name='typed_tag',
        ),
        migrations.AlterUniqueTogether(
            name='actortaggedthing',
            unique_together={('typed_tag', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='directortaggedthing',
            unique_together={('typed_tag', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='languagetaggedthing',
            unique_together={('typed_tag', 'content_object')},
        ),
    ]
